{
	"version": 1497272786,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/block.png",
		"images/player-sheet0.png",
		"images/teleport-sheet0.png",
		"images/playercontroler-sheet0.png",
		"images/tiledbackground2.png",
		"images/tower-sheet0.png",
		"images/bullet-sheet0.png",
		"images/baseturret-sheet0.png",
		"images/camera-sheet0.png",
		"images/borntokill-sheet0.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground6.png",
		"media/inaki - phoenix.ogg",
		"media/inaki - rewind.ogg",
		"media/tarpey - conglomerate.ogg",
		"media/thomas vx - stranger.ogg",
		"media/wontolla - shape in the snow.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}